name: Lint 

on: 
    push: 
    pull_request: 

jobs:
    check: 
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v6
            
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy
            - name: Linting using clippy
              run: cargo clippy  --all-features -- -D warnings
